server:
  port: 20000
  servlet:
    context-path: /product-service
spring:
  application:
    name: product-service
  datasource:
    name: product-service
    url: jdbc:mysql://localhost:3306/shop_sw?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    host: localhost
    port: 6379
    password: redis
mapper:
  mappers:
    - com.caoyong.commons.BaseDao
  not-empty: false
  identity: MYSQL
mybatis:
  typeAliasesPackage: com.caoyong.sw.bean
  mapperLocations: classpath*:dao/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  file:
    name: ./logs/product-service/product-service.log
  level:
    com.caoyong: debug