server:
  port: 20001
  servlet:
    context-path: /programs-service
spring:
  application:
    name: programs-service
  datasource:
    name: programs-service
    url: jdbc:mysql://localhost:3306/vlb_yzb?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    host: localhost
    port: 6379
    password: redis
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: test
    template:
      default-receive-queue: CY_PROGRAMS_SERVICE_QUEUE
mapper:
  mappers:
    - com.caoyong.commons.BaseDao
  not-empty: false
  identity: MYSQL
mybatis:
  typeAliasesPackage: com.caoyong.yzb.bean
  mapperLocations: classpath*:dao/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  file:
    name: ./logs/programs-service/programs-service.log
  level:
    com.caoyong: debug
