server:
  port: 2000
  servlet:
    context-path: /mall-api
spring:
  application:
    name: mall-api
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
swagger-ui:
  show: true