server:
  port: 2000
  servlet:
    context-path: /mall-api
spring:
  application:
    name: mall-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
