server:
  port: 2001
  servlet:
    context-path: /programs-api
spring:
  application:
    name: programs-api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
