server:
  port: 2001
  servlet:
    context-path: /programs-api
spring:
  application:
    name: programs-api
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
swagger-ui:
  show: true